---
title: "Regression caret"
author: "Abhigyan Kishor"
date: "2023-11-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This example uses the `tidyverse` suite of packages.

```{r, load_tidyverse}
library(tidyverse)
library(ggplot2)
library(caret)
```

### Read data

The code chunk below reads in the final project data.

```{r, read_final_data}
df <- readr::read_csv("paint_project_train_data.csv", col_names = TRUE)
```

```{r}
df_scaled <- df %>%
  select(R, G, B, Hue, Saturation, Lightness, outcome) %>% 
  mutate(outcome = ifelse(outcome == 1, 'event', 'non_event'),
         outcome = factor(outcome, levels = c('event', 'non_event')))
```

```{r}
set.seed(1234)
```

### Comparing models on accuracy

```{r}
my_ctrl_acc <- trainControl(method = 'repeatedcv', number = 5, repeats = 3, savePredictions = 'all')
my_metrics_acc <- "Accuracy"
```

```{r}
formulas <- list('outcome ~ .',
                 'outcome ~ Lightness + Saturation + (R + G + B + Hue)^2',
                 'outcome ~ (Lightness + Saturation)*(R + G + B + Hue)*(R + G + B + Hue)',
                 'outcome ~ (Lightness + Saturation + Hue)*(R + G + B)')
```

```{r}
formula_to_glm_model <- function(form, met, ctrl) {
  caret::train(form %>% as.formula(),
        data = df_scaled,
        method = 'glm',
        preProcess = c('center', 'scale'),
        metric = met,
        trControl = ctrl)
}
```

```{r}
glm_default_acc <- tibble::tibble(
  formula = formulas,
  models = purrr::map(formulas, formula_to_glm_model, my_metrics_acc, my_ctrl_acc)
)
```

```{r}
formula_to_enet_model <- function(form, met, ctrl) {
  caret::train(form %>% as.formula(),
        data = df_scaled,
        method = 'glmnet',
        preProcess = c('center', 'scale'),
        metric = met,
        trControl = ctrl)
}
```

```{r}
enet_default_acc <- tibble::tibble(
  formula = formulas[2:3],
  models = purrr::map(formula, formula_to_enet_model, my_metrics_acc, my_ctrl_acc)
)
```

```{r}
formula_to_enet_tune_model <- function(form, enet_default, met, ctrl) {
  my_lambda_grid <- exp(seq(log(min(enet_default$results$lambda)),
                          log(max(enet_default$results$lambda)),
                          length.out = 25))
  enet_grid <- expand.grid(alpha = seq(0.1, 1, by = 0.1),
                           lambda = my_lambda_grid)
  caret::train(form %>% as.formula(),
        data = df_scaled,
        method = 'glmnet',
        preProcess = c('center', 'scale'),
        tuneGrid = enet_grid,
        metric = met,
        trControl = ctrl)
}
```

```{r}
enet_tune_acc <- tibble::tibble(
  formula = formulas[2:3],
  models = purrr::map2(formula, enet_default_acc$models, formula_to_enet_tune_model, my_metrics_acc, my_ctrl_acc, .progress = TRUE)
)
```

```{r}
plot(enet_tune_acc$models[[1]], xTrans = log)
```

```{r}
plot(enet_tune_acc$models[[2]], xTrans = log)
```

```{r}
plot( varImp(enet_tune_acc$models[[1]]) )
```

```{r}
plot( varImp(enet_tune_acc$models[[2]]), top = 20 )
```

```{r}
nnet_default_acc <- train( outcome ~ .,
                       data = df_scaled,
                       method = 'nnet',
                       metric = my_metrics_acc,
                       preProcess = c("center", "scale"),
                       trControl = my_ctrl_acc,
                       trace = FALSE)
```

```{r}
nnet_grid <- expand.grid(size = c(5, 10, 20),
                         decay = exp(seq(-6, 2, length.out=11)))
```

```{r}
nnet_tune_acc <- train( outcome ~ .,
                       data = df_scaled,
                       method = 'nnet',
                       metric = my_metrics_acc,
                       preProcess = c("center", "scale"),
                       tuneGrid = nnet_grid,
                       trControl = my_ctrl_acc,
                       trace = FALSE)
```

```{r}
plot(nnet_tune_acc, xTrans=log)
```

```{r}
rf_default_acc <- train( outcome ~ .,
                     data = df_scaled,
                     method = 'rf',
                     metric = my_metrics_acc,
                     trControl = my_ctrl_acc,
                     importance = TRUE)
```

```{r}
plot( varImp(rf_default_acc) )
```

```{r}
xgb_default_acc <- caret::train(outcome ~ ., data = df_scaled,
                            metric = my_metrics_acc,
                            trControl = my_ctrl_acc,
                            method = 'xgbTree',
                            verbosity = 0,
                            nthread = 1)
```

```{r}
plot(xgb_default_acc)
```

```{r}
xgb_grid <- expand.grid(nrounds = seq(25, 50, by = 25),
                        max_depth = c(3,6,9,12),
                        eta = c(0.25, 0.5, 1) * xgb_default_acc$bestTune$eta,
                        gamma = xgb_default_acc$bestTune$gamma,
                        colsample_bytree = xgb_default_acc$bestTune$colsample_bytree,
                        min_child_weight = xgb_default_acc$bestTune$min_child_weight,
                        subsample = xgb_default_acc$bestTune$subsample)
```

```{r}
xgb_tune_acc <- caret::train(outcome ~ ., data = df_scaled,
                            metric = my_metrics_acc,
                            trControl = my_ctrl_acc,
                            method = 'xgbTree',
                            verbosity = 0,
                            tuneGrid = xgb_grid,
                            nthread = 1)
```

```{r}
plot(xgb_tune_acc)
```

```{r}
plot( varImp(xgb_default_acc) )
```

```{r}
plot( varImp(xgb_tune_acc) )
```

```{r}
caret_acc_compare <- resamples(
  list(
    glm_default_acc_1 = glm_default_acc$models[[1]],
    glm_default_acc_2 = glm_default_acc$models[[2]],
    glm_default_acc_3 = glm_default_acc$models[[3]],
    glm_default_acc_4 = glm_default_acc$models[[4]],
    enet_default_acc_1 = enet_default_acc$models[[1]],
    enet_default_acc_2 = enet_default_acc$models[[2]],
    enet_tune_acc_1 = enet_tune_acc$models[[1]],
    enet_tune_acc_2 = enet_tune_acc$models[[2]],
    nnet_default_acc = nnet_default_acc,
    nnet_tune_acc = nnet_tune_acc,
    rf_default_acc = rf_default_acc,
    xgb_default_acc = xgb_default_acc,
    xgb_tune_acc = xgb_tune_acc
  )
)
```

```{r}
caret_acc_compare %>% dotplot(metric = my_metrics_acc)
```

```{r}
acc_models_list <- list(
    glm_default_acc_1 = glm_default_acc$models[[1]],
    glm_default_acc_2 = glm_default_acc$models[[2]],
    glm_default_acc_3 = glm_default_acc$models[[3]],
    glm_default_acc_4 = glm_default_acc$models[[4]],
    enet_default_acc_1 = enet_default_acc$models[[1]],
    enet_default_acc_2 = enet_default_acc$models[[2]],
    enet_tune_acc_1 = enet_tune_acc$models[[1]],
    enet_tune_acc_2 = enet_tune_acc$models[[2]],
    nnet_default_acc = nnet_default_acc,
    nnet_tune_acc = nnet_tune_acc,
    rf_default_acc = rf_default_acc,
    xgb_default_acc = xgb_default_acc,
    xgb_tune_acc = xgb_tune_acc
  )

for(name in names(acc_models_list)) {
  acc_models_list[[name]] %>% readr::write_rds(paste(name, '.rds', sep = ''))
}
```

### Comparing models based on ROC/AUC

```{r}
my_ctrl_roc <- trainControl(method = 'repeatedcv', number = 5, repeats = 3,
                            summaryFunction = twoClassSummary,
                            classProbs = TRUE,
                            savePredictions = TRUE)

my_metrics_roc <- 'ROC'
```

```{r}
glm_default_roc <- tibble::tibble(
  formula = formulas,
  models = purrr::map(formulas, formula_to_glm_model, my_metrics_roc, my_ctrl_roc)
)
```

```{r}
enet_default_roc <- tibble::tibble(
  formula = formulas[2:3],
  models = purrr::map(formula, formula_to_enet_model, my_metrics_roc, my_ctrl_roc)
)
```

```{r}
enet_tune_roc <- tibble::tibble(
  formula = formulas[2:3],
  models = purrr::map2(formula, enet_default_roc$models, formula_to_enet_tune_model, my_metrics_roc, my_ctrl_roc)
)
```

```{r}
plot(enet_tune_roc$models[[1]], xTrans = log)
```

```{r}
plot(enet_tune_roc$models[[2]], xTrans = log)
```

```{r}
plot(varImp(enet_tune_roc$models[[1]]))
```

```{r}
plot(varImp(enet_tune_roc$models[[2]]), top = 20)
```

```{r}
nnet_default_roc <- train( outcome ~ .,
                       data = df_scaled,
                       method = 'nnet',
                       metric = my_metrics_roc,
                       preProcess = c("center", "scale"),
                       trControl = my_ctrl_roc,
                       trace = FALSE)
```

```{r}
nnet_grid <- expand.grid(size = c(5, 10, 20),
                         decay = exp(seq(-6, 2, length.out=11)))
```

```{r}
nnet_tune_roc <- train( outcome ~ .,
                       data = df_scaled,
                       method = 'nnet',
                       metric = my_metrics_roc,
                       preProcess = c("center", "scale"),
                       tuneGrid = nnet_grid,
                       trControl = my_ctrl_roc,
                       trace = FALSE)
```

```{r}
plot(nnet_tune_roc, xTrans=log)
```

```{r}
rf_default_roc <- train( outcome ~ .,
                     data = df_scaled,
                     method = 'rf',
                     metric = my_metrics_roc,
                     trControl = my_ctrl_roc,
                     importance = TRUE)
```

```{r}
plot( varImp(rf_default_roc) )
```

```{r}
xgb_default_roc <- caret::train(outcome ~ ., data = df_scaled,
                            metric = my_metrics_roc,
                            trControl = my_ctrl_roc,
                            method = 'xgbTree',
                            verbosity = 0,
                            nthread = 1)
```

```{r}
plot(xgb_default_roc)
```

```{r}
xgb_grid <- expand.grid(nrounds = seq(25, 50, by = 25),
                        max_depth = c(3,6,9,12),
                        eta = c(0.25, 0.5, 1) * xgb_default_roc$bestTune$eta,
                        gamma = xgb_default_roc$bestTune$gamma,
                        colsample_bytree = xgb_default_roc$bestTune$colsample_bytree,
                        min_child_weight = xgb_default_roc$bestTune$min_child_weight,
                        subsample = xgb_default_roc$bestTune$subsample)
```

```{r}
xgb_tune_roc <- caret::train(outcome ~ ., data = df_scaled,
                            metric = my_metrics_roc,
                            trControl = my_ctrl_roc,
                            method = 'xgbTree',
                            verbosity = 0,
                            tuneGrid = xgb_grid,
                            nthread = 1)
```

```{r}
plot(xgb_tune_roc)
```

```{r}
plot( varImp(xgb_default_roc) )
```

```{r}
plot( varImp(xgb_tune_roc) )
```

```{r}
caret_roc_compare <- resamples(
  list(
    glm_default_roc_1 = glm_default_roc$models[[1]],
    glm_default_roc_2 = glm_default_roc$models[[2]],
    glm_default_roc_3 = glm_default_roc$models[[3]],
    glm_default_roc_4 = glm_default_roc$models[[4]],
    enet_default_roc_1 = enet_default_roc$models[[1]],
    enet_default_roc_2 = enet_default_roc$models[[2]],
    enet_tune_roc_1 = enet_tune_roc$models[[1]],
    enet_tune_roc_2 = enet_tune_roc$models[[2]],
    nnet_default_roc = nnet_default_roc,
    nnet_tune_roc = nnet_tune_roc,
    rf_default_roc = rf_default_roc,
    xgb_default_roc = xgb_default_roc,
    xgb_tune_roc = xgb_tune_roc
  )
)
```

```{r}
caret_roc_compare %>% dotplot(metric = my_metrics_roc)
```

```{r}
roc_models_list <- list(
    glm_default_roc_1 = glm_default_roc$models[[1]],
    glm_default_roc_2 = glm_default_roc$models[[2]],
    glm_default_roc_3 = glm_default_roc$models[[3]],
    glm_default_roc_4 = glm_default_roc$models[[4]],
    enet_default_roc_1 = enet_default_roc$models[[1]],
    enet_default_roc_2 = enet_default_roc$models[[2]],
    enet_tune_roc_1 = enet_tune_roc$models[[1]],
    enet_tune_roc_2 = enet_tune_roc$models[[2]],
    nnet_default_roc = nnet_default_roc,
    nnet_tune_roc = nnet_tune_roc,
    rf_default_roc = rf_default_roc,
    xgb_default_roc = xgb_default_roc,
    xgb_tune_roc = xgb_tune_roc
  )

for(name in names(roc_models_list)) {
  roc_models_list[[name]] %>% readr::write_rds(paste(name, '.rds', sep = ''))
}
```
